<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Eloquent::unguard();

        $this->call('ManagerTableSeeder');

        $this->command->info('Managers table seeded!');

        $this->call('OfficeTableSeeder');

        $this->command->info('Managers table seeded!');

        $this->call('UserTableSeeder');

        $this->call('StateTableSeeder');

        $this->call('CityTableSeeder');
	}

}

class ManagerTableSeeder extends Seeder {

    public function run()
    {
        DB::table('managers')->delete();


        Manager::create(array('id' => 1, 'name' => "Mona Phillips", 'title' =>"Broker Owner", 'license' => "CA 01415909", 'description' =>  'Mona Phillips began her career as a Realtor in 2004 and in 2013 decided to become a Realty ONE Group affiliate.  Realty ONE Group Elite is a company well suited to its name. The real estate professionals are hand selected, ensuring the company is comprised of only the very best in the industry.', 'image' => "Antioch_Broker.jpg", 'email' =>  "mona.phillips@comcast.net"));
        Manager::create(array('id' => 2, 'name' => "Wendell Jones", 'title' =>"Broker Owner", 'license' => "CA 01857914", 'description' =>  'Wendell Jones has extensive experience in handling a variety of real estate matters. In addition to being a licensed real estate broker, Jones is also a licensed attorney. He shows dedication and persistence when helping his clients navigate their complex real estate matters.', 'image' => "Campbell_Broker.jpg", 'email' =>  " wendell@rogainfinity.com"));
        Manager::create(array('id' => 3, 'name' => "Tina King", 'title' =>"Regional Manager", 'license' => "", 'description' =>  'Tina began her journey in real estate sales in 1995. She has coached and consulted over 1,000 agents, several managers and owners, and has consistently increased agent awareness through coaching and top notch support. She works at a fast pace and keeps a positive attitude within an environment of productivity and fun.', 'image' => "Carlsbad_Manager.jpg", 'email' =>  "tinak@realtyonegroup.com"));
        Manager::create(array('id' => 4, 'name' => "Linda Rocha", 'title' =>"Branch Manager", 'license' => "", 'description' =>  'Linda Rocha has been in real estate for over three decades, and has cultivated a career based upon customer care and thorough market knowledge.  She boasted sales in excess of 100 million while in the field and was a former broker/owner. Her experience provides a solid foundation upon which to build her agents careers.', 'image' => "Corona_Manager.jpg", 'email' => "lindar@realtyonegroup.com"));
        Manager::create(array('id' => 5, 'name' => "Jenny Yuan", 'title' =>"Broker Owner", 'license' => "CA 00991362", 'description' =>  'With 24 years of real estate experience, Jenny Yuan’s goal has always been to help her clients sell their home at top dollar and buy the home of their dreams at a price they can afford.  She coaches her agents to fulfill their clients’ needs with the highest level of professionalism and integrity.', 'image' => "Cupertino Broker.jpg"));
        Manager::create(array('id' => 6, 'name' => "Parm Rahi", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Entering the real estate market in 2005, Parm combines his enthusiasm for the real estate business with proven experience. His sense of humor and his commitment to service has made him a customer favorite. Parm is very attentive and understands exactly what his buyers and sellers want and need.', 'image' => "Emeryville Broker.jpg"));
        Manager::create(array('id' => 7, 'name' => "Ranbir Atwal", 'title' =>"Broker Owner", 'license' => "CA 01427001", 'description' =>  'Realty ONE Group American has two brokers of record: Ranbir Atwal and Pal Singh. Together they bring an extensive experience of over 40 years. Atwal has been involved in the real estate industry for the past 9 years. Singh has been involved in the real estate industry since 1989.', 'image' => "Fremont Broker.jpg"));
        Manager::create(array('id' => 8, 'name' => "Jaime Genie", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'In 1997 Jaime applied his vast knowledge and skills to pursue a career in real estate.  He quickly developed a reputation as a hardworking, honest, and caring real estate broker. Jaime has made it a priority to keep up with current real estate trends, news, and technology.', 'image' => "Glendora Broker.jpg"));
        Manager::create(array('id' => 9, 'name' => "Ron Pascual", 'title' =>"Branch Manager", 'license' => "CA 01148347", 'description' =>  'Ron brings his leadership and motivational skills to Realty ONE Group as a Corporate Broker. "I am entrusted with the privilege to provide our community with the best and brightest real estate agents and with the support of our Team of Professionals, I am certain we will exceed your expectations!"- Ron Pascual.', 'image' => "Huntington Beach Manager.jpg"));
        Manager::create(array('id' => 10, 'name' => "Michael Davar", 'title' =>"Regional Manager", 'license' => "CA 00847909", 'description' =>  'Michael Davar has been a Realtor for more than 25 years.  His skills are finely tuned and he applies them to dealing with today’s market and its unique challenges.  He cares for his clients and treats them the way he would want to be treated if he were the client, which has led him to achieve great success in Orange County real estate.', 'image' => "Irvine Manager.jpg"));
        Manager::create(array('id' => 11, 'name' => "Carole Lynch", 'title' =>"Designated Broker", 'license' => "CA 01274306", 'description' =>  'Carole Lynch has been a successful broker/owner of her company Lynch Associates Real Estate for 3 years.  Carol Lynch’s client-first philosophy quickly earned her a reputation as a trustworthy advocate for buyers and sellers. Her ability to persevere makes her a valuable asset.', 'image' => "Laguna Niguel Broker.jpg"));
        Manager::create(array('id' => 12, 'name' => "Stephen Miller", 'title' =>"Branch Manager", 'license' => "CA 01011860", 'description' =>  'Stephen Miller is a U.S. Army military leader and service-oriented business professional with over twenty-five years of experience in the industry.  His skill sets have been honed through many years as a California Real Estate Broker in residential and commercial real estate.', 'image' => "Mission Viejo Manager.jpg"));
        Manager::create(array('id' => 13, 'name' => "Jason Nowak", 'title' =>"Branch Manager", 'license' => "CA 01895743", 'description' =>  'Jason has had over 10 years of leadership, sales, coaching and training experience in the San Diego Real Estate industry.  His core values focus on accountability through encouragement as well as communicating with others clearly, professionally and respectfully.', 'image' => "Rancho Bernardo Manager.jpg"));
        Manager::create(array('id' => 14, 'name' => "Paul LePage", 'title' =>"Branch Manager", 'license' => "CA 01035915", 'description' =>  'For 25 years Paul has excelled in every aspect of the real estate profession in Southern California. The ability to counsel realtors and clients in stressful transactional situations is one of Paul\'s many talents that he brings to Realty ONE Group.', 'image' => "Rancho Cucamonga Manager.jpg"));
        Manager::create(array('id' => 15, 'name' => "John Schulte", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'John Schulte’s long track record for agent development and support has enabled him to take pride in the development of some of the most successful agents in the Inland Empire. Whether you are new or seasoned, we invite you to experience the Power of ONE by joining the office where the Champions come to succeed!', 'image' => "Riverside Broker.jpg"));
        Manager::create(array('id' => 16, 'name' => "Rosemarie Figueroa", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Rosemarie began her California real estate career as a salesperson in 1991 and became a Broker in 1998.  She has held the position of President and is currently a member of the Board of Directors of the Filipino American Real Estate Professionals Association (FAREPA) and is also a Board Member of SAMCAR, CVAR and BAREIS.', 'image' => "San Mateo Broker.jpg"));
        Manager::create(array('id' => 17, 'name' => "Navid Ali", 'title' =>"Broker Owner", 'license' => "CA 01142036", 'description' =>  'Navid has been a California licensed broker since 2003. He is an expert in the marketing and negotiating of all aspects of real estate and is incredibly invested in customer service.  He enjoys helping real estate agents develop their business and implement real estate systems to further increase productivity.', 'image' => "San Ramon Broker.jpg"));
        Manager::create(array('id' => 18, 'name' => "Patrick Raach", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Patrick H. Raach has been in the real estate industry for over 26 years. Real estate is in Patrick’s blood and he loves helping his clients become savvy real estate investors while honing his agents’ skills to make them some of the best trained agents in the business.', 'image' => ""));
        Manager::create(array('id' => 19, 'name' => "Ron Pascual", 'title' =>"Branch Manager", 'license' => "", 'description' =>  'Ron brings his leadership and motivational skills to the professionals at Realty ONE Group. "I am entrusted with the privilege to provide our community with the best and brightest real estate agents and with the support of our Team of Professionals, I am certain we will exceed your expectations!"- Ron Pascual', 'image' => "Seacliff Manager.jpg"));
        Manager::create(array('id' => 20, 'name' => "Barbara Baker", 'title' =>"Broker Owner", 'license' => "CA 00524780", 'description' =>  'Licensed in the industry for 35+ years, Barbara has not lost her excitement and passion, and is enthusiastic as ever about her industry. As a broker/owner with prior experience in operating her own company, she readily and willingly shares her knowledge and insight that comes from being a veteran professional. With her "agent centric" attitude, she strongly believes that the agent is the most significant aspect of her brokerage. Agents will find her open door policy welcoming and refreshing.', 'image' => "Temecula Broker.jpg"));
        Manager::create(array('id' => 21, 'name' => "Michael Szakos", 'title' =>"Broker Owner", 'license' => "CA 01473073", 'description' =>  'Michael Szakos’ high attention to detail and results-driven approach have equated to completing over 500 transactions in the past five years. Being hands on and in the trenches daily allows him to stay in tune with market trends and experience firsthand the unique opportunities and challenges of the market.', 'image' => "Ventura Broker.jpg"));
        Manager::create(array('id' => 22, 'name' => "Lori Souza", 'title' =>"Managing Broker", 'license' => "AZ BR537336000", 'description' =>  'Lori Souza’s vast experience in selling residential and multifamily real estate, including contract law and negotiation, makes her a valuable asset to our team.   Lori ran her own brokerage firm in Chandler for eight years and in addition is a licensed real estate instructor in the State of Arizona. Lori especially enjoys the aspect of training, mentoring and coaching.', 'image' => "Gilbert Broker.jpg"));
        Manager::create(array('id' => 23, 'name' => "Ron Copus", 'title' =>"Managing Broker", 'license' => "AZ BR004648000", 'description' =>  'Ron moved to the Valley of the Sun in 1976, his quick success in real estate led him to become a broker in 1979. Building on his reputation of honesty and knowledge, he has spent several years as a broker helping new and experienced agents build successful real estate careers.', 'image' => "Glendale Broker.jpg"));
        Manager::create(array('id' => 24, 'name' => "Leah Wolfe-Kraemer", 'title' =>"Branch Manager", 'license' => "", 'description' =>  'Leah Wolfe-Kraemer is a native Phoenician who became a licensed REALTOR® in 2005. A top-producing agent in both of her previous companies, Leah was recognized for her commitment to helping other agents grow their businesses.  She attends various real estate courses and designation curriculum to ensure she is always “in the know”.', 'image' => "Goodyear Broker.jpg"));
        Manager::create(array('id' => 25, 'name' => "Jim Sexton", 'title' =>"Designated Broker", 'license' => "", 'description' =>  'Jim Sexton CRB, GRI sets the bar for both ethics and integrity in our industry. For over 25 years, he has volunteered countless hours to better this industry for home buyers, home sellers and REALTORS®, and has chaired many committees. Jim is a three-time ‘REALTOR® of the Year’ recipient and the only two-time Dean B. Service Memorial Award recipient.', 'image' => "Paradise Valley Broker.jpg"));
        Manager::create(array('id' => 26, 'name' => "KC Cyga", 'title' =>"Managing Broker", 'license' => "", 'description' =>  'KC Cyga has been in management for over 15 years as both a manager and designated broker. She has been recognized for being very successful in training, coaching, and encouraging agents to financial success. She believes with proper training, direction, determination and desire, real estate can be very rewarding career.', 'image' => "Scottsdale Broker.jpg"));
        Manager::create(array('id' => 27, 'name' => "Bill Powers", 'title' =>"Branch Manager", 'license' => "", 'description' =>  'Bill Powers has extensive experience in his real estate career, spending 29 years with Realty Executives before joining the Realty ONE Group team. Bill eventually became the President and CEO of Realty Executives International, successfully transforming some of the most distressed regions in the nation into thriving franchise markets.', 'image' => "North Scottsdale Manager.jpg"));
        Manager::create(array('id' => 28, 'name' => "Brian White", 'title' =>"Managing Broker", 'license' => "", 'description' =>  'Brian White brings with him a wealth of knowledge acquired over 8,000 unique transactions. He has had over 10 years of coaching and business development experience, including extensive knowledge in internet lead generation, lead development and internet marketing.', 'image' => "Tempe Broker.jpg"));
        Manager::create(array('id' => 29, 'name' => "Tom Coury Sr.", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Tom Coury Sr. is a Native Arizonan and licensed broker for over 37 years. He has had first-hand experience in understanding how rules, regulations and various laws have affected the real estate industry. Despite these changes, one thing has always remained; our rights and title to the most lasting commodity of all time, our land.', 'image' => "Tucson Broker.jpg"));
        Manager::create(array('id' => 30, 'name' => "Gary Carlson", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Gary\'s experience stems not only in the Real Estate environment but in other business sectors having managed sales teams, closed multi-million dollar contracts and constantly ranked top in performance. This has led to a well-rounded career that can help bring value to all.', 'image' => "Denver Broker.jpg"));Manager::create(array('id' => 31, 'name' => "Kathryn Bovard", 'title' =>"Managing Broker", 'license' => "", 'description' =>  'Kathryn has been a licensed broker for over 20 years and enjoys coaching agents in business and real estate systems, increasing productivity, exit strategy and team building. She is licensed to teach continuing education classes through the Nevada Real Estate Commission and is serving as the GLVR 2011 Treasurer.', 'image' => "Green Valley Broker.jpg"));Manager::create(array('id' => 32, 'name' => "David Squier", 'title' =>"Managing Broker", 'license' => "NV BS.0144109.MGR", 'description' =>  'David started his real estate career in 1988 and has experienced every type of market. He worked at Prudential American Group for over nine years, building a team that quickly became one of Prudential\'s top "Mega Teams". He possesses a natural ability for training, coaching, mentoring and business development.', 'image' => "Northwest Broker.jpg"));
        Manager::create(array('id' => 33, 'name' => "Damon Caldwell", 'title' =>"Designated Broker", 'license' => "NV B.0143673.CORP", 'description' =>  'Damon started his career in 2001. By 2006, he hired a team manager to run the day to day operations in order to pursue his true passion of training and coaching agents on a larger scale. From 2006 to 2011 Damon managed an office of over 200 agents as well as five employees, and organized sales meetings, events and training programs.', 'image' => "Southwest Broker.jpg"));
        Manager::create(array('id' => 34, 'name' => "Wally Kowis", 'title' =>"Managing Broker", 'license' => "NV BS.0030607.MGR", 'description' =>  'An industry expert with successful experience in full life cycle Recruiting, Training, Coaching and Business Development, Wally has a proven ability to foster relationships with the newest of business professionals to the most seasoned entrepreneurs.', 'image' => "Summerlin Broker.jpg"));
        Manager::create(array('id' => 35, 'name' => "Jeanette Harpole", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Upon moving to Eugene in 2008, Jeannette has coached several of the top buyer’s agents in town and is the premier expert on short sales in Oregon.  She has discovered her passion and natural ability for training, coaching, and business development.', 'image' => "Eugene Broker.jpg"));
        Manager::create(array('id' => 36, 'name' => "Tomas Castella", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Tomas Castella’s diverse and extensive business background, combined with his commercial and residential real estate experience, makes him uniquely qualified to lead and advise agents and their clients with all their real estate needs.  Tomas’s real estate experience includes brokerage, development, and investment.', 'image' => "Dallas Broker.jpg"));
        Manager::create(array('id' => 37, 'name' => "Chance Brown", 'title' =>"Broker Owner", 'license' => "", 'description' =>  'Chance began his career in real estate by working for one of the largest home builders in the US. During his time there, Chance was driven by a passion to help and educate people.  He is a graduate of the Texas Realtors Leadership Program and a recipient of NRG “20 Under 40 Rising Stars in Real Estate” award.', 'image' => "Houston Broker.jpg"));
        Manager::create(array('id' => 38, 'name' => "Vincent Kyan", 'title' =>"Branch Manager", 'license' => "CA 00984120", 'description' =>  'Vincent Kyan joins Realty ONE Group with over 25 years of real estate experience.  His previous roles found him excelling as a real estate broker, manager, trainer, and professional business coach. Kyan is passionate about helping agents at his office achieve greater success.', 'image' => "Anaheim_Manager.jpg"));

    }

}

class OfficeTableSeeder extends Seeder {

    public function run()
    {
        DB::table('offices')->delete();

        Office::create(array('name' => "Anaheim", 'phone' => "714.602.2600", 'address' => "2300 E. Katella Suite 100 Anaheim, CA 92806", 'city_id' => 8, 'description' =>  'The most desirable executive area in Anaheim, known as the Platinum Triangle, is home to our 6,400 sq. ft. office. Offering escrow and mortgage professionals on site, this location holds 3 state-of-the-art conference rooms, a large training room and gorgeous views of Angel Stadium.', 'manager_id' => "38", 'lat' => 33.837961, 'lng' => -117.870495, 'image' => "Anaheim_Office.jpg"));
        Office::create(array('name' => "Antioch", 'phone' => "925.366.8900", 'address' => "5119 Lone Tree Way Antioch, CA 94531", 'city_id' => 9, 'description' =>  'Centrally located on the City border of Antioch and Brentwood in the heart of the Venture Commerce Business Center. This facility offers a sprawling 3500 square feet of space, 2 Conference Rooms, Large Training Facility, 10 Private Offices, 10 Work Stations and an Agent Resource Center.', 'manager_id' => "1", 'lat' => 37.962171663265, 'lng' => -121.76522813265, 'image' => "Antioch_Office.jpg"));
        Office::create(array('name' => "Campbell", 'phone' => "408.377.2700", 'address' => "910 East Hamilton Ave Suite 100 Campbell, CA 95008", 'city_id' => 10, 'description' =>  'Realty ONE Group Infinity has extensive experience in a variety of real estate matters such as loan modifications, short sales, and deeds in lieu of foreclosure. We offer comprehensive and innovative training, education, and support to all of our professionals.', 'manager_id' => "2", 'lat' => 37.294257167857, 'lng' => -121.93804653571, 'image' => "Campbell_Office.jpg"));
        Office::create(array('name' => "Carlsbad", 'phone' => "760.607.3230", 'address' => "2701 Loker Ave West Suite 150 Carlsbad, CA 92010", 'city_id' => 11, 'description' =>  'This state-of-the-art facility will provide the very latest in comfort and technology for both agents and clients alike with ample conference areas, access to our in-house Mortgage and Escrow partners, and full time Branch Manager – all of which points to our dedication to client service and satisfaction.', 'manager_id' => "3", 'lat' => 33.133719775862, 'lng' => -117.25867860345, 'image' => "Carlsbad_Office.jpeg"));
        Office::create(array('name' => "Corona", 'phone' => "951.547.8400", 'address' => "1260 Corona Pointe Suite 102 Corona, CA 92879", 'city_id' => 12, 'description' =>  'Monumental is the best way to describe our Corona office. Located east of the 15 and 91 interchange, this beautiful 6,800 sq. ft. real estate office stands proudly in the Corona Pointe business center. This facility has 17 private offices, 10 work stations, and 2 state-of-the-art conference rooms.', 'manager_id' => "4", 'lat' => 33.752748, 'lng' => -117.474266, 'image' => "Corona_Office.jpg"));
        Office::create(array('name' => "Cupertino", 'phone' => "408.255.3978", 'address' => "1072 S. De Anza Blvd Suite B205 Cupertino, CA 92129", 'city_id' => 13, 'description' =>  'World Properties was founded in 2004 and aims to provide the highest degree of professionalism to real estate clients in the Bay Area. They are committed to consistently upholding the principles of integrity, honesty, knowledge, and enthusiasm when helping their clients, supporting their agents, and serving their community.', 'manager_id' => "5", 'lat' => 36.721278200001, 'lng' => -122.0313942, 'image' => ""));
        Office::create(array('name' => "Emeryville", 'phone' => "510.421.1455", 'address' => "1900 Powell St Emeryville, CA 94608", 'city_id' => 14, 'description' =>  'Realty ONE Group Allure’s prestigious location puts it right in the middle of a cluster of corporate headquarters. The offices have a modern contemporary look with access to multiple amenities including Wi-Fi access, 2 conference rooms, a large training facility and a resource center for our agents.', 'manager_id' => "6", 'lat' => 37.837876448819, 'lng' => -122.2978380315, 'image' => ""));
        Office::create(array('name' => "Fremont", 'phone' => "510.651.7111", 'address' => "42820 Albrae St. Fremont, CA 94538", 'city_id' => 15, 'description' =>  'Realty ONE Group American has agents based in the Bay Area and Central Valley. The agents are experienced in short sales, residential and commercial real estate.  The company’s motto: “Customers First” and offers the finest real estate customer care in the area. All clients are treated with the highest degree of professionalism.', 'manager_id' => "7", 'lat' => 37.507938, 'lng' => -121.973372, 'image' => ""));
        Office::create(array('name' => "Glendora", 'phone' => "626.650.0370", 'address' => "1345 S Grand Avenue Glendora, CA 91740", 'city_id' => 16, 'description' =>  'Minutes away from Downtown Glendora, the state of the art office has every amenity that a successful agent will need. Located close to the 210 and 10 freeways, the office is the perfect location and environment in which to build your successful career. Come grow with us!', 'manager_id' => "8", 'lat' => 34.114965777778, 'lng' => -117.87255522222, 'image' => "Glendora Office .jpg"));
        Office::create(array('name' => "Huntington Beach", 'phone' => "714.698.5300", 'address' => "19126 Magnolia Street Suite 101 Huntington Beach, CA 92646", 'city_id' => 34, 'description' =>  'Light and open with lots of windows, our 4,500 sq. ft. Huntington Beach office is on the southeast corner of Magnolia and Garfield. Our location offers 10 private offices, 9 work stations, and a state-of-the-art conference room.', 'manager_id' => "9", 'lat' => 33.683187722222, 'lng' => -117.97134586111, 'image' => "Huntington Beach Office.jpg"));
        Office::create(array('name' => "Irvine", 'phone' => "949.783.2400", 'address' => "4010 Barranca Pkwy Suite 120 Irvine, CA 92604", 'city_id' => 17,'description' =>  'Centrally located at the intersection of Culver Drive and the Barranca Parkway, our 8,000 sq. ft. Irvine location has quickly grown to our largest office in California. This facility has 15 private offices, 13 work stations, a large training room, and state-of-the-art conference room.', 'manager_id' => "10", 'lat' => 33.6840155, 'lng' => -117.808169, 'image' => "Irvine Office.jpg"));
        Office::create(array('name' => "Laguna Niguel", 'phone' => "949.297.2020", 'address' => "23811 Aliso Creek Road Suite 181 Laguna Niguel, CA 92677", 'city_id' => 18,'description' =>  'Located in the Laguna Design Center, our Laguna Niguel office is surrounded by high-end design stores, a calming courtyard and a private cafe. This 2-story facility has 15 private offices, 16 work stations, and 2 state-of-the-art conference rooms.', 'manager_id' => "11", 'lat' => 33.198039000004, 'lng' => -118.1035, 'image' => "Laguna Niguel Office.jpg"));
        Office::create(array('name' => "Mission Viejo", 'phone' => "949.783.2499", 'address' => "25910 Acero Suite 100 Mission Viejo, CA 92691", 'city_id' => 35,'description' =>  'With gorgeous views of Saddleback Mountain, our 7,468 sq. ft. office is located minutes away from Lake Mission Viejo. Our Mission Viejo office has 17 private offices, 10 work stations and a state-of-the-art conference room available for REALTORS® to work with their clients.', 'manager_id' => "12", 'lat' => 33.617430875, 'lng' => -117.67760125, 'image' => "Mission Viejo Office.jpg"));
        Office::create(array('name' => "Rancho Bernardo", 'phone' => "619.823.2994", 'address' => "11440 W Bernardo Ct Suite 100 Rancho Bernardo, CA 92127", 'city_id' => 19,'description' =>  'This state-of-the-art facility will provide the very latest in comfort and technology for both agents and clients alike with ample conference areas, access to our in-house Mortgage and Escrow partners, and full time Branch Manager – all of which points to our dedication to client service and satisfaction.', 'manager_id' => "13", 'lat' => 33.018655, 'lng' => -117.060866, 'image' => ""));
        Office::create(array('name' => "Rancho Cucamonga", 'phone' => "909.694.0160", 'address' => "10681 Foothill Blvd Suite 140 Rancho Cucamonga, CA 91730", 'city_id' => 20,'description' =>  'Located on Historic Route 66 our state-of–the-art office offers our agents and clients a comfortable place to meet and discuss their real estate dreams. The ample conference areas and access to our in-house Mortgage & Escrow partners, and full time Branch Manager rounds out our dedication to client satisfaction', 'manager_id' => "14", 'lat' => 34.106494515152, 'lng' => -117.57545828283, 'image' => ""));
        Office::create(array('name' => "Riverside", 'phone' => "951.565.8105", 'address' => "19322 Jesse Lane Riverside, CA 92508", 'city_id' => 21, 'description' =>  'The Realty ONE Group Champions office is strategically located to serve the Greater Riverside Inland Valleys region of Riverside County.  Our team of highly trained and successful agents provides a level of dedicated client focus and support rarely experienced in the industry.', 'manager_id' => "15", 'lat' => 33.891132, 'lng' => -117.326750, 'image' => "Riverside Office.jpg"));
        Office::create(array('name' => "San Mateo", 'phone' => "650.376.3328", 'address' => "1021 S El Camino Real San Mateo, CA 94402", 'city_id' => 22, 'description' =>  'Realty ONE Group-Alliance is committed to providing the finest, full-service real estate brokerage. They provide clients and partners with unparalleled opportunities for personal and professional development by giving excellent support and assistance in education, skills and resources.', 'manager_id' => "16", 'lat' => 37.556786214286, 'lng' => -122.319104, 'image' => ""));
        Office::create(array('name' => "San Ramon", 'phone' => "800.448.9806", 'address' => "2355 San Ramon Valley Blvd Suite 100 San Ramon, CA 94583", 'city_id' => 23, 'description' =>  'Our San Ramon Valley office is a sleek, contemporary and modern facility. This centralized bay area location is strategically located on San Ramon Valley Blvd conveniently off the 680 Crown Canyon exit. The office boasts 10 private offices, 10 workstations and a state of the art conference room.', 'manager_id' => "17", 'lat' => 37.776017229167, 'lng' => -121.9782165, 'image' => "San Ramon Office.jpg"));
        Office::create(array('name' => "Santa Clarita", 'phone' => "661.253.3000", 'address' => "25129 The Old Road Suite 100 Santa Clarita, CA 91381", 'city_id' => 24, 'description' =>  'Realty ONE Group Solutions is located at the entrance to Santa Clarita Valley, just off the Golden State Freeway (I5). Conveniently located to service the neighboring communities of the San Fernando and Antelope Valleys.', 'manager_id' => "18", 'lat' => 37.862148, 'lng' => -122.168022, 'image' => ""));
        Office::create(array('name' => "Seacliff", 'phone' => "714.274.2720", 'address' => "2124 Main Street Seacliff, CA 92648", 'city_id' => 25, 'description' =>  'Located in the heart of Sea Cliff Village in Huntington Beach, our prestigious office is located just off Main Street and Yorktown Avenue across from the Huntington Beach Civic Center. Featuring 6 private offices and a large training room.', 'manager_id' => "19", 'lat' => 33.680033333333, 'lng' => -118.00179222222, 'image' => ""));
        Office::create(array('name' => "Temecula", 'phone' => "951.216.2000", 'address' => "41463 Margarita Rd Suite 100 Temecula, CA 92591", 'city_id' => 26,'description' =>  'Proud and honored to be the FIRST Franchise for Realty ONE Group. Situated in a 6,000 sq. ft. space we feature private offices, spacious conference rooms, open work areas and a state of the art technology platform. The foundation of our business is a passion for servicing others with the emphasis on providing superior client care.', 'manager_id' => "20", 'lat' => 33.531788, 'lng' => -117.1815732, 'image' => ""));
        Office::create(array('name' => "Ventura", 'phone' => "805.978.5764", 'address' => "940 E Santa Clara St Suite 100 Ventura, CA 93001", 'city_id' => 27,'description' =>  'Realty ONE Group Summit is located in the heart of downtown Ventura. With its offices just a block away from the beach and the historic Ventura Pier, Realty ONE Group Summit exudes Ventura’s laid back sophistication. Nestled among Craftsman cottages, the office mimics mid-century modern architecture, with clean lines and bright windows.', 'manager_id' => "21", 'lat' => 34.279546367347, 'lng' => -119.28607163265, 'image' => "Ventura Office.jpg"));
        Office::create(array('name' => "Gilbert", 'phone' => "480.321.8100", 'address' => "3530 S Val Vista Dr Suite 114 Gilbert, AZ 85297", 'city_id' => 1,'description' =>  'Backing up to the San Tan 202 Freeway just off of Val Vista Dr., our 4,000 sq. ft. Gilbert office sits in Copper Point Business Park. Featuring 12 private offices, 12 work stations, and 3 state-of-the-art conference rooms and a large training facility, this office serves residents and REALTORS® in the Southeast Valley.', 'manager_id' => "22", 'lat' => 33.288169852941, 'lng' => -111.7554525, 'image' => "Gilbert Office.jpg"));
        Office::create(array('name' => "Glendale", 'phone' => "623.334.3744", 'address' => "17235 N 75th Ave Suite C-190 Glendale, AZ 85308", 'city_id' => 2,'description' =>  'Serving the West Valley, our Glendale office is nestled inside the northwest curve of the Loop 101 near the intersection of 75th Ave and Bell Rd. Our 3,400 sq. ft. facility holds 10 private offices, 9 work stations and 2 state-of-the-art conference rooms.', 'manager_id' => "23", 'lat' => 33.640860514085, 'lng' => -112.22030797887, 'image' => "Glendale Office.jpg"));
        Office::create(array('name' => "Goodyear", 'phone' => "623.552.3773", 'address' => "2950 N Litchfield Road Goodyear, AZ 85395", 'city_id' => 3,'description' =>  'Our beautiful 4,000+ square foot Goodyear location boasts 12 private offices, luxurious conference rooms and state-of-the-art technology. The space offers our agents and clients alike a conveniently located and comfortable place to meet and discuss their real estate dreams.', 'manager_id' => "24", 'lat' => 33.4776178, 'lng' => -112.3584061875, 'image' => "Goodyear Office.jpg"));
        Office::create(array('name' => "Paradise Valley", 'phone' => "602.953.4000", 'address' => "11211 N Tatum Boulevard Suite 200 Paradise Valley, AZ 85028", 'city_id' => 4,'description' =>  'Overlooking the 16th green of the Stone Creek Golf Course, our 10,000 sq. ft. Paradise Valley facility has views that extend all the way to the McDowell Mountains. This facility holds 3 conference rooms, a large training room, 14 private offices, and 26 work stations.', 'manager_id' => "25", 'lat' => 33.462492767442, 'lng' => -111.97549224419, 'image' => "Paradise Valley Office.jpg"));
        Office::create(array('name' => "Scottsdale", 'phone' => "480.315.1240", 'address' => "7975 N Hayden Rd Suite A-101 Scottsdale, AZ 85258", 'city_id' => 5,'description' =>  'Clients consistently comment on the gorgeous courtyard next to our 6,000 sq. ft. Scottsdale office. With quick access to the Loop 101 by way of Via de Ventura, this facility has 14 private offices, 7 work stations, and 2 state-of-the-art conference rooms.', 'manager_id' => "26", 'lat' => 33.552678608696, 'lng' => -111.899028, 'image' => "Scottsdale Office.jpg"));
        Office::create(array('name' => "North Scottsdale", 'phone' => "480.285.0000", 'address' => "17550 N Perimeter Drive Suite 160 Scottsdale, AZ 85255", 'city_id' => 5,'description' =>  'Our 4,000 square foot North Scottsdale office sits off of 101 and Princess Drive and is managed by real estate veteran Bill Powers. This state-of-the-art facility provides the very latest in comfort and technology to agents and clients alike, boasting 9 private offices, 2 conference rooms and 8 work stations.', 'manager_id' => "27", 'lat' => 33.645139081081, 'lng' => -111.89794613514, 'image' => "North Scottsdale Office.jpg"));
        Office::create(array('name' => "Tempe", 'phone' => "480.215.2356", 'address' => "2141 E Broadway Rd Suite 101 Tempe, AZ", 'city_id' => 6,'description' =>  'With quick access to the Southeast Valley, our state-of-the-art 4,400 sq. ft. Tempe office is located in the extraordinary Broadway 101 Business Center west of the Loop 101. This facility has a dozen work stations, 3 state-of-the-art conference rooms, and 12 private offices.', 'manager_id' => "28", 'lat' => 33.407496, 'lng' => -111.89471647368, 'image' => "Tempe Office.jpg"));
        Office::create(array('name' => "Tucson", 'phone' => "520.742.5663", 'address' => "6970 North Oracle Road Suite 110 Tucson, AZ 85704", 'city_id' => 7,'description' =>  'Realty ONE Group Great American is Southern Arizona\'s latest full-service location. Located at 6970 North Oracle Road Suite #110 in Tucson, Arizona, our newly remodeled offices offer over 3,600 Sq. Ft. of work space, including individual private offices. Give us a call at: 520-742-5663. We are hiring new agents today!', 'manager_id' => "29", 'lat' => 32.333026714286, 'lng' => -110.97718814286, 'image' => ""));
        Office::create(array('name' => "Denver", 'phone' => "303.798.4300", 'address' => "7399 S Tucson Way Suite C1 Centennial, CO 80112", 'city_id' => 28,'description' =>  'Realty ONE Group Premier is located in the heart of the Denver Tech Center. Our office is centrally located in the fastest growing, upscale communities of the Front Range. Our office delivers an upscale mountain chalet feel with beautiful views of the mountains, along with a fun and energizing atmosphere.', 'manager_id' => "30", 'lat' => 39.930782, 'lng' => -105.074287, 'image' => ""));
        Office::create(array('name' => "Green Valley", 'phone' => "702.898.7575", 'address' => "2831 St Rose Parkway Suite 100 Henderson, NV 89052", 'city_id' => 29,'description' =>  'Our Green Valley office embodies a true modern business facility. Located on Parkway and Eastern Avenue, this location boasts 21 private offices, 21 work stations, and 5 state-of-the-art conference rooms.', 'manager_id' => "31", 'lat' => 36.031669045455, 'lng' => -115.100456, 'image' => "Green Valley Office.jpg"));
        Office::create(array('name' => "Northwest", 'phone' => "702.898.0101", 'address' => "5550 Painted Mirage Road Suite 140 Las Vegas, NV 89149", 'city_id' => 30,'description' =>  'Located northwest of Summerlin Parkway and the 95 freeway interchange, our 8,200 sq. ft. facility in Northwest Las Vegas has 12 private offices, 26 work stations, a training room with seating capacity of 22, and 2 state-of-the-art conference rooms.', 'manager_id' => "32", 'lat' => 36.262062909091, 'lng' => -115.25657177273, 'image' => "Northwest Office.jpg"));
        Office::create(array('name' => "Southwest", 'phone' => "702.898.1010", 'address' => "8395 W Sunset Road Suite 190 Las Vegas, NV 89113", 'city_id' => 30,'description' =>  'Looking towards the mountains southwest of Las Vegas, our 17,000 sq. ft. office is located in the Centra Point Commercial Park just north of the 215 Freeway near Durango Drive. The facility includes 19 work stations, 26 private offices, a training room with seating capacity of 30, and 3 state-of-the-art conference rooms.', 'manager_id' => "33", 'lat' => 36.070274077181, 'lng' => -115.26092493289, 'image' => "Southwest Office.jpg"));
        Office::create(array('name' => "Summerlin", 'phone' => "702.898.1221", 'address' => "10750 W Charleston Blvd Suite 180 Las Vegas, NV 89135", 'city_id' => 30,'description' =>  'Located in the Howard Hughes Center, our 10,000 sq. ft. Summerlin office is one of the highest-producing offices in Las Vegas. This location includes 15 work stations, a training room with seating capacity for 60, 25 private offices, and 2 state-of-the-art conference rooms.', 'manager_id' => "34", 'lat' => 36.158934795302, 'lng' => -115.32434430537, 'image' => "Summerlin Office.jpg"));
        Office::create(array('name' => "Eugene", 'phone' => "541.743.8999", 'address' => "1500 Valley River Drive Suite 190 Eugene, OR 97401", 'city_id' => 31,'description' =>  'Centrally located close to the Valley River Center, our 5,700 sq. ft. office in Eugene has 14 private offices, 15 drop in stations, a training room, and 2 state-of-the-art conference rooms.', 'manager_id' => "35", 'lat' => 44.071148601719, 'lng' => -123.1099852063, 'image' => ""));
        Office::create(array('name' => "Dallas", 'phone' => "214.599.8008", 'address' => "2500 Routh Street Dallas, TX 75201", 'city_id' => 32,'description' =>  'Realty ONE Group Partners is conveniently located in the heart of Dallas Texas in the upscale Turtle Creek area, and adjacent to exclusive Highland Park and dynamic Uptown area. The office is just minutes away from Downtown Dallas, the Park Cities, Preston Hollow and other Dallas’s best neighborhoods.', 'manager_id' => "36", 'lat' => 32.796329, 'lng' => -96.801741, 'image' => ""));
        Office::create(array('name' => "Houston", 'phone' => "832.678.4770", 'address' => "12777 Jones Road Suite 400 Houston, TX 77070", 'city_id' => 33,'description' =>  'Located in the heart of NW Houston, Realty ONE Group Lone Star is right in the middle of one of the Houston market\'s largest areas for growth. Located on the top floor of Denmark House, we offer a first-class place for agents to meet with clients, get more education, or come have some fun with their teammates.', 'manager_id' => "37", 'lat' => 29.958895902174, 'lng' => -95.585026152174, 'image' => ""));
    }

}
